PreNat/Controllers/PatientMasterController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Office.Interop.Word;
using PreNat.Entities;
using PreNat.Services;
using PreNat.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PreNat.Controllers
{
    public class PatientMasterController : Controller
    {
        // GET: PatientMaster
        public ActionResult Index(string SearchTerm = "")
        {
            MainListingViewModel model = new MainListingViewModel();
            if (User.IsInRole("Admin"))
            {
                model.PatientMasters = PatientMasterServices.Instance.GetPatientMasters(SearchTerm);
            }
            else
            {
                model.PatientMasters = PatientMasterServices.Instance.GetPatientMasters(User.Identity.GetUserId(), SearchTerm);

            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Action(int ID = 0)
        {
            MainActionViewModel model = new MainActionViewModel();
            if (ID != 0)
            {
                var patientmaster = PatientMasterServices.Instance.GetPatientMaster(ID);
                model.ID = patientmaster.ID;
                model.Name = patientmaster.Name;
                model.Surnames = patientmaster.Surnames;
                model.Type_of_Identity = patientmaster.Type_of_Identity;
                model.Department_of_residence = patientmaster.Department_of_residence;
                model.City_Municipality_of_residence = patientmaster.City_Municipality_of_residence;
                model.Address_of_residence = patientmaster.Address_of_residence;
                model.Telephones_Landline = patientmaster.Telephones_Landline;
                model.Cell_Phone = patientmaster.Cell_Phone;
              
                model.Date_of_birth = patientmaster.Date_of_birth;
                model.Age = patientmaster.Age;
                model.Race_DANE_Information = patientmaster.Race_DANE_Information;
                model.Ethnicity_DANE_Information = patientmaster.Ethnicity_DANE_Information;
                model.Level_of_Education = patientmaster.Level_of_Education;
                model.Marital_status = patientmaster.Marital_status;
                model.Affiliation_regime = patientmaster.Affiliation_regime;
                model.EPS_IPS = patientmaster.EPS_IPS;
                model.Tbc = patientmaster.Tbc;
                model.Diabetes = patientmaster.Diabetes;
                model.Hypertension = patientmaster.Hypertension;
                model.Eclampsia = patientmaster.Eclampsia;
                model.Preeclampsia = patientmaster.Preeclampsia;
                model.Surgery = patientmaster.Surgery;
                model.Infertility = patientmaster.Infertility;
                model.Cardiopathy = patientmaster.Cardiopathy;
                model.Nephropathy = patientmaster.Nephropathy;
                model.Violence = patientmaster.Violence;
                model.HIV = patientmaster.HIV;
                model.Migraine = patientmaster.Migraine;
                model.Thromboembolic = patientmaster.Thromboembolic;
                model.BMI_29 = patientmaster.BMI_29;
                model.BMI_39 = patientmaster.BMI_39;
                model.Disc_Sang = patientmaster.Disc_Sang;
                model.Other = patientmaster.Other;
                model.ReliableFUM = patientmaster.ReliableFUM;
                model.UltrasoundObstetrics = patientmaster.UltrasoundObstetrics;
                model.FPP = patientmaster.FPP;
                model.FPC = patientmaster.FPC;
                model.ProbableDateOfDelivery = patientmaster.ProbableDateOfDelivery;
                model.ProbableDateOfConception = patientmaster.ProbableDateOfConception;


                model.TetanusDiphtheriaNo = patientmaster.TetanusDiphtheriaNo;
                model.TetanusDiphtheriaYesPrevPreg = patientmaster.TetanusDiphtheriaYesPrevPreg;
                model.TetanusDiphtheriaYesDuringPreg = patientmaster.TetanusDiphtheriaYesDuringPreg;
                model.TetanusDiphtheria_Date = patientmaster.TetanusDiphtheria_Date;
                model.TetanusDiphtheria_Dozes = patientmaster.TetanusDiphtheria_Dozes;
                model.TetanusCheck = patientmaster.TetanusCheck;

                model.TdapNo = patientmaster.TdapNo;
                model.TdapYesPrevPreg = patientmaster.TdapYesPrevPreg;
                model.TdapYesDuringPreg = patientmaster.TdapYesDuringPreg;
                model.Tdap_Date = patientmaster.Tdap_Date;
                model.Tdap_Dozes = patientmaster.Tdap_Dozes;
                model.TdapCheck = patientmaster.TdapCheck;

                model.InfluenzaNo = patientmaster.InfluenzaNo;
                model.InfluenzaYesPrevPreg = patientmaster.InfluenzaYesPrevPreg;
                model.InfluenzaYesDuringPreg = patientmaster.InfluenzaYesDuringPreg;
                model.Influenza_Date = patientmaster.Influenza_Date;
                model.Influenza_Dozes = patientmaster.Influenza_Dozes;
                model.InfluencaCheck = patientmaster.InfluencaCheck;

                model.RubellaNo = patientmaster.RubellaNo;
                model.RubellaYesPrevPreg = patientmaster.RubellaYesPrevPreg;
                model.RubellaYesDuringPreg = patientmaster.RubellaYesDuringPreg;
                model.Rubella_Date = patientmaster.Rubella_Date;
                model.Rubella_Dozes = patientmaster.Rubella_Dozes;
                model.RubellaCheck = patientmaster.RubellaCheck;

                model.Hepatitis_ANo = patientmaster.Hepatitis_ANo;
                model.Hepatitis_AYesPrevPreg = patientmaster.Hepatitis_AYesPrevPreg;
                model.Hepatitis_AYesDuringPreg = patientmaster.Hepatitis_AYesDuringPreg;
                model.Hepatitis_A_Date = patientmaster.Hepatitis_A_Date;
                model.Hepatitis_A_Dozes = patientmaster.Hepatitis_A_Dozes;
                model.Hepatitis_ACheck = patientmaster.Hepatitis_ACheck;

                model.Hepatitis_BNo = patientmaster.Hepatitis_BNo;
                model.Hepatitis_BYesPrevPreg = patientmaster.Hepatitis_BYesPrevPreg;
                model.Hepatitis_BYesDuringPreg = patientmaster.Hepatitis_BYesDuringPreg;
                model.Hepatitis_B_Date = patientmaster.Hepatitis_B_Date;
                model.Hepatitis_B_Dozes = patientmaster.Hepatitis_B_Dozes;
                model.Hepatitis_BCheck = patientmaster.Hepatitis_BCheck;

                model.Group = patientmaster.Group;
                model.SanguineoGroup = patientmaster.SanguineoGroup;
                model.VDRL = patientmaster.VDRL;
                model.Syphilis = patientmaster.Syphilis;
                model.VIH_L = patientmaster.VIH_L;
                model.PlannedPregnancy = patientmaster.PlannedPregnancy;
                model.DesiredPregnancy = patientmaster.DesiredPregnancy;
                model.PreconceptionCounseling = patientmaster.PreconceptionCounseling;
                model.ContraceptiveFailure = patientmaster.ContraceptiveFailure;
                model.DefinitiveMethod = patientmaster.DefinitiveMethod;
                model.Failure = patientmaster.Failure;
                model.Gestation = patientmaster.Gestation;
                model.NoOfPregnancy = patientmaster.NoOfPregnancy;
                model.Delivery = patientmaster.Delivery;
                model.Term = patientmaster.Term;
                model.Preterm = patientmaster.Preterm;
                model.Vaginal = patientmaster.Vaginal;
                model.Cesareas = patientmaster.Cesareas;
                model.Abortions = patientmaster.Abortions;
                model.Gemerales = patientmaster.Gemerales;
                model.Ectopic = patientmaster.Ectopic;
                model.Obitus = patientmaster.Obitus;
                model.Molas = patientmaster.Molas;
                model.Live_Births = patientmaster.Live_Births;
                model.FUM = patientmaster.FUM;
                model.WeeksPregnant = patientmaster.WeeksPregnant;
                model.Positive_HCG_presence = patientmaster.Positive_HCG_presence;
                model.Positive_HCG_presence_Date = patientmaster.Positive_HCG_presence_Date;
                model.Upload_document1 = patientmaster.Upload_document1;
                model.Positive_TV_ultrasound = patientmaster.Positive_TV_ultrasound;
                model.Positive_TV_ultrasound_Date = patientmaster.Positive_TV_ultrasound_Date;
                model.Upload_document2 = patientmaster.Upload_document2;
                model.PregnancyConfirm = patientmaster.PregnancyConfirm;
                model.SmokerActive = patientmaster.SmokerActive;
                model.PassiveSmoking = patientmaster.PassiveSmoking;
                model.ConsumeAlcohol = patientmaster.ConsumeAlcohol;
                model.ConsumeAlucinogenos = patientmaster.ConsumeAlucinogenos;
                model.DomesticViolence = patientmaster.DomesticViolence;
                model.GestationalFormula=patientmaster.GestationalFormula;
                model.ReportStatus = patientmaster.ReportStatus;
                model.ReasonsLists = patientmaster.ReasonsList.Split(',').ToList();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Action(MainActionViewModel model, string Step)
        {
            var ReasonsList = new List<string>();
            var ReasonsListForHigh = new List<string>();
            if (Session["PatientMasterID"] != null)
            {
              

                var patientmaster = PatientMasterServices.Instance.GetPatientMaster(int.Parse(Session["PatientMasterID"].ToString()));
                patientmaster.ID = patientmaster.ID;
                patientmaster.CreatedBy = User.Identity.GetUserId();
     

                if (Step == "Step1")
                {
                    patientmaster.Name = model.Name;
                    patientmaster.Surnames = model.Surnames;

PreNat/Views/PatientMaster/Index.cshtml
@model PreNat.ViewModels.MainListingViewModel
@{
    ViewBag.Title = "Index";
}

<div class="card">
    <div class="card-body">
        <h2 class="card-title">Patient Masters</h2>
        <hr />


        <div class="row mb-3">
            <div class="col col-lg-12">
                <form>
                    <div class="input-group">
                        <input type="text" name="searchterm" class="form-control" placeholder="Search." value="@Model.SearchTerm">

                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i> Search</button>
                            <a class="btn btn-outline-secondary" href="@Url.Action("Index", "PatientMaster")"><i class="fas fa-redo-alt mr-1"></i> Reset</a>
                            <a href="@Url.Action("Action", "PatientMaster")" class="btn btn-outline-success" type="button" ><i class="fas fa-plus mr-1"></i> Create</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col col-lg-12">
                <div id="actionContainer">
                    @{
                        Html.RenderPartial("_Listing", Model);
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
    </div>
</div>

<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href"),
        })
            .done(function (response) {
                $("#actionModal .modal-dialog").html(response);
            });
    });
</script>

PreNat/Views/PatientMaster/_Delete.cshtml
@model PreNat.ViewModels.MainActionViewModel

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                <span>Delete Patient Master</span>
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="ID" value="@Model.ID" />
            </form>
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete this Patient Master: @Model.Name?
            </div>
        </div>
        <div class="modal-footer">
            <button id="actionButton" type="button" class="btn btn-danger"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
        </div>
    </div>
}

<script>
	$("#actionButton").click(function () {
		$.ajax({
			url: '@Url.Action("Delete", "PatientMaster")',
			type: "post",
			data: $("#actionForm").serialize()
		})
		.done(function () {

            window.location.href = "@Url.Action("Index","PatientMaster")";

		});
	});
</script>

PreNat/Views/PatientMaster/_Listing.cshtml
@model PreNat.ViewModels.MainListingViewModel
@{
    ViewBag.Title = "_Listing";
}


<div class="row">

    <div class="col-lg-12 grid-margin stretch-card">
        @if (Model.PatientMasters.Count() != 0)
        {
            <div class="card">

                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>

                               
                                <th>
                                    Name
                                </th>
                               
                                <th>Surname</th>
                                <th>City</th>


                                <th>
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.PatientMasters)
                            {
                            <tr>

                                <td>@item.Name</td>
                                <td>@item.Surnames</td>
                                <td>@item.City_Municipality_of_residence</td>
                                <td>
                                    <a href="@Url.Action("Action", "PatientMaster", new {ID=item.ID })" class="btnEdit btn btn-info btn-icon-text"><i class="mdi mdi-pencil"></i> EDIT</a>
                                    <button data-href="@Url.Action("Delete", "PatientMaster", new { ID = item.ID })" type="button" class="data-btn btn btn-danger btn-icon-text" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="mdi mdi-delete"></i>DELETE</button>

                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }
        else
        {

            <div class="alert alert-warning col-md-12" role="alert">
                Sorry! No records exist.
            </div>
        }
    </div>
</div>

<script>
   


</script>